version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    volumes:
      - "./data/zookeeper:/opt/zookeeper-3.4.6/data"
  kafka:
    image: wurstmeister/kafka:0.10.0.1
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    links:
      - zookeeper
    volumes:
      - "./data/kafka:/kafka"
  database:
    image: postgres:9.5.3
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
